#pragma once

#define I2C1_SCL_PIN B8
#define I2C1_SDA_PIN B9

#define I2C2_SCL_PIN B10
#define I2C2_SDA_PIN B11

#define I2C_DRIVER I2CD1

#define OLED_FADE_OUT
#define OLED_FADE_OUT_INTERVAL 5

#define OLED_FONT_H "font.c"

//#define OLED_SCROLL_TIMEOUT 5000
#define OLED_TIMEOUT 0

//#define OLED_SCROLL_SPEED 100
#define OLED_DISPLAY_HEIGHT 32
#define OLED_DISPLAY_WIDTH 128

//#define DEBUG_MATRIX_SCAN_RATE

#define BOOTMAGIC_LITE_ROW 1
#define BOOTMAGIC_LITE_COLUMN 0

#define LEADER_TIMEOUT 300
#define LEADER_PER_KEY_TIMING
#define LEADER_NO_TIMEOUT
