BOOTMAGIC_ENABLE = yes
ENCODER_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c
I2C_DRIVER_REQUIRED = yes
CONSOLE_ENABLE = yes
RAW_ENABLE = yes
WPM_ENABLE = yes
OS_DETECTION_ENABLE = yes
LEADER_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes

SRC += oled.c